apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-quickstart
spec:
  version: 8.15.1
  count: 1
  http:
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            nodePort: 32002
            port: 3002
            protocol: TCP
            targetPort: 3002
  elasticsearchRef:
    name: quickstart
  config:
    ent_search.external_url: https://192.168.49.2:32002
    kibana.host: https://192.168.49.2:30885