apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.15.0
  http:
    service:
      spec:
        type: NodePort
  count: 1
  elasticsearchRef:
    name: quickstart
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: quickstart
    logs:
      elasticsearchRefs:
        - name: quickstart