apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.15.1
  http:
    service:
      spec:
        type: NodePort
  count: 1
  elasticsearchRef:
    name: quickstart
  enterpriseSearchRef:
    name: enterprise-search-quickstart
#  confid:
#    enterpriseSearch:
#      host: 'https://enterprise-search-quickstart-ent-http.elk.svc:3002'
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: quickstart
    logs:
      elasticsearchRefs:
        - name: quickstart
