apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: es-dev # We'll rename to es-dev

resources:
- ../../base

patches:
  - path: patch.yaml
    target:
      kind: Elasticsearch
      name: quickstart
