apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elk
spec:
  version: 8.17.3
  http:
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            nodePort: 30601
            port: 5601
            protocol: TCP
            targetPort: 5601
  count: 1
  elasticsearchRef:
    name: quickstart
  #  enterpriseSearchRef:
  #    name: enterprise-search-quickstart
  #  confid:
  #    enterpriseSearch:
  #      host: 'https://enterprise-search-quickstart-ent-http.elk.svc:3002'
  # Set the IP to your minikube node Ip from `minikube profile list
  config:
    server.publicBaseUrl: "https://192.168.58.2:30601/"
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: quickstart
    logs:
      elasticsearchRefs:
        - name: quickstart